# [学習力][Level1] 続的に学習時間を確保できる
# [実装力][Level1] コードを手元で動かすことができる
# [Ruby][Level1] メソッドを自作し使うことができる
# [Ruby][Level1] 変数を宣言し代入することができる
# [Ruby][Level1] 条件分岐を使うことができる
# [Ruby][Level1] 繰り返し処理を行うことができる
# [Ruby][Level2] ブロックを使った配列の処理ができる(advanced)
# [Ruby][Level2] ハッシュを使うことができる(advanced)
# [Ruby][Level2] シンボルを使うことができる(advanced)
# [オブジェクト指向][Level2] オブジェクト指向が何かを説明できる
# [オブジェクト指向][Level2] オブジェクト指向を使うことができる
# [Ruby][Level2] モジュールを説明できる(advanced)
# [Ruby][Level2] 例外処理を使うことができる
# [Ruby][Level2] 外部ライブラリを使うことができる(advanced)
# [Ruby][Level2] デバッガを活用してデバッグができる(advanced)
# [Ruby][Level2] 静的解析ツールを使うことができる(advanced)
