@startuml blackjack

class Card {
  +rank: String
  +suit: String
  +value: Integer
  +cardDisplay(): Void
}

class Deck {
  +cards:
  +draw(): Card
  +printDeck(): Void
  +shuffle(): Void
}

class Dealer {
  +startGame(de): Dealer
  (static) +startGame(
    amountOfPlayers: int, gameMode: String): Dealer
  +initialCards():
  +
}


class Game {
  {static} +main(args: String[]): Void
}

Game "1" *-- "1" Player : has
Game "1" *-- "1" Dealer : has
Game "1" *-- "1" Deck : has
Player "1" *-- "1" Hand : has
Dealer "1" *-- "1" Hand : has
Hand "1" *-- "*" Card : has

@enduml
